version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sohoaform-sqlserver  
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourVeryStrong!Password123
      - MSSQL_PID=Express
      - MSSQL_TCP_PORT=1433
    ports:
      - "0.0.0.0:1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    restart: unless-stopped
    networks:
      - sohoaform-network
  

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: sohoaform-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=SoHoaFormDB;User Id=sa;Password=YourVeryStrong!Password123;TrustServerCertificate=true;
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver
    restart: unless-stopped
    networks:
      - sohoaform-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: sohoaform-frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - sohoaform-network

volumes:
  sqldata:

networks:
  sohoaform-network:
    driver: bridge