version: '3.8'

services:
  # Backend API Service
  api:
    build:
      context: ./SoHoaFormApi
      dockerfile: Dockerfile
    ports:
      - "5047:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./SoHoaFormApi/uploads:/app/uploads
    networks:
      - sohoaform-network
    restart: unless-stopped

  # Frontend Service  
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://161.248.147.59:5047/api
    depends_on:
      - api
    networks:
      - sohoaform-network
    restart: unless-stopped

networks:
  sohoaform-network:
    driver: bridge

volumes:
  uploads: