version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sohoaform-sqlserver  
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
      - MSSQL_TCP_PORT=1433
      - MSSQL_AGENT_ENABLED=true
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    restart: unless-stopped
    networks:
      - sohoaform-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong!Passw0rd -Q 'SELECT 1' -C"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 60s

  # API Backend
  api:
    build: 
      context: ./SoHoaFormApi
      dockerfile: Dockerfile
    container_name: sohoaform-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__SoHoaFormConnectionString=Server=sqlserver,1433;Database=SoHoaForm;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true;
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    restart: unless-stopped
    networks:
      - sohoaform-network

  # Frontend
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: sohoaform-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - sohoaform-network

volumes:
  sqldata:

networks:
  sohoaform-network:
    driver: bridge